# aries_cloudagent.protocols.didexchange.v1_0.messages package

## Submodules

## aries_cloudagent.protocols.didexchange.v1_0.messages.complete module

## aries_cloudagent.protocols.didexchange.v1_0.messages.problem_report_reason module

DID Exchange problem report reasons.


### _class_ aries_cloudagent.protocols.didexchange.v1_0.messages.problem_report_reason.ProblemReportReason(value)
Bases: [`Enum`](https://docs.python.org/3/library/enum.html#enum.Enum)

Supported reason codes.


#### COMPLETE_NOT_ACCEPTED(_ = 'complete_not_accepted_ )

#### INVITATION_NOT_ACCEPTED(_ = 'invitation_not_accepted_ )

#### REQUEST_NOT_ACCEPTED(_ = 'request_not_accepted_ )

#### REQUEST_PROCESSING_ERROR(_ = 'request_processing_error_ )

#### RESPONSE_NOT_ACCEPTED(_ = 'response_not_accepted_ )

#### RESPONSE_PROCESSING_ERROR(_ = 'response_processing_error_ )
## aries_cloudagent.protocols.didexchange.v1_0.messages.request module

## aries_cloudagent.protocols.didexchange.v1_0.messages.response module
